[api.urls]

login = 'https://api.invertironline.com/token'
operaciones = 'https://api.invertironline.com/api/v2/operaciones'


[api.dataframe]

operaciones_colunms = [
    'numero',
    'fecha_orden',
    'tipo',
    'estado',
    'mercado',
    'simbolo',
    'cantidad',
    'monto',
    'modalidad',
    'precio',
    'fecha_operacion',
    'cantidad_operacion',
    'precio_operacion',
    'monto_operacion',
    'plazo',
]

[execution]

start_date = '2021-01-01 00:00:00'
